### ISSUE TITLE
stopSpeechRecognition() is undefined

### ISSUE THREAD

**Issue by simk0024** [goxr3plus/java-google-speech-api#1]
I have this error when compiling the given sample:
_The method stopSpeechRecognition() is undefined for the type GSpeechDuplex_
at line 
`duplex.stopSpeechRecognition();`

Please advise.

Btw, is this the same source code as the SpeechDemo.jar released [here ](https://github.com/lkuza2/java-speech-api/releases)?

**Comment by goxr3plus** [comment]
Hello my friend , the code is similar but not the same , i have added new things . Look how you are downloading the library ?

If you are using Maven , Gradle etc (WHICH I ADVICE YOU TO DO)

### Add it to your project using JitPack :

https://jitpack.io/private#goxr3plus/java-google-speech-api

### Step 1. Add the JitPack repository to your build file
``` XML
<repositories>
	<repository>
	   <id>jitpack.io</id>
	   <url>https://jitpack.io</url>
        </repository>
</repositories>
```

###  Step 2. Add the dependency
``` XML
<dependency>
   <groupId>com.github.goxr3plus</groupId>
   <artifactId>java-google-speech-api</artifactId>
   <version>V2.1</version> 
</dependency>
```

should bring you all the needed jars and the latest version of this library .

**Comment by goxr3plus** [comment]
#simk0024 Is your problem solved ?

**Comment by simk0024** [comment]
Sorry that I missed your reply earlier
and Yes, it worked!
Formerly, the program failed because I was using 
`<dependency>
   <groupId>com.google.cloud</groupId>
   <artifactId>google-cloud-speech</artifactId>
   <version>0.26.0-alpha</version> 
</dependency>`

**Comment by goxr3plus** [comment]
:) Happy to hear.
