### ISSUE TITLE
Is this based on Google accounts?

### ISSUE THREAD

**Issue by stefan-reich** [goxr3plus/java-google-speech-api#10]
I STRONGLY suggest using my Google-account-free speech recognition based on Chrome instead. It's fully Java-integrated too. More (somewhere) on [my home page](https://BotCompany.de), LOL.

**Comment by goxr3plus** [comment]
I see some Swing there, oh yeaahhhh :)

**Comment by goxr3plus** [comment]
Do you have the code Open Source somewhere?

**Comment by stefan-reich** [comment]
Yeah, the module is [here](http://code.botcompany.de/1009816). It's in my language JavaX, but you can click on "Pure Java version".
