### ISSUE TITLE
Google Translate's Url has changed

### ISSUE THREAD

**Issue by walklown** [goxr3plus/java-google-speech-api#11]
Google Translate's Url has changed to `https://translate.google.cn/translate_a/single`.

**Comment by goxr3plus** [comment]
Can you help me fix it :) ?

**Comment by TurtleBeatboxer** [comment]
Hey, I can fix that
I really want to so I can get my first open-source commit done :)

**Comment by goxr3plus** [comment]
Great drop a pull request ☺

**Comment by TurtleBeatboxer** [comment]
Sorry that it took so long I just fought with unit test also 
Thank you that I could participate  <3
