### ISSUE TITLE
Maven and import (user) problem

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/java-google-speech-api#9]
I have a pom.xml file which includes the repository and dependency given in the readme.md file. It seems to work.

```xml
        <dependency>
            <groupId>com.github.goxr3plus</groupId>
            <artifactId>java-google-speech-api</artifactId>
            <version>8.0.0</version>
        </dependency>
```

But I cannot 
```java
import com.goxr3plus.speech.util.Complex;
```
only 
```java
import com.darkprograms.speech.util.Complex;
```

To me, it looks that i'm not getting the files of this repository, but probably those of an upstream library. What am I doing wrong?

Second issue, unrelated or not: Using the Maven dependency, I can only get version 8.0.0, not version V2.1.

**Comment by goxr3plus** [comment]
Hm have i release V2.1? 8.0.0 is the latest one that should be used, i fixed some stuff.

Ow abiut the other think, did changed the packages before or after the release od 8.0.0.

It's been a long time.

Is the library working for you?

**Comment by HelgeStenstrom** [comment]
I shouldn't combine two issues.

The version issue: XR3Player currently has this:
```xml
 		<dependency>
			<groupId>com.github.goxr3plus</groupId>
			<artifactId>java-google-speech-api</artifactId>
			<version>V2.1</version>
		</dependency>
```

**Comment by HelgeStenstrom** [comment]
Is the library working for me?
I'm not really trying to use it at this time. Just checking if I can tell Maven to depend on it. And as far as my unit test of Complex(1,0) is concerned, yes it works. (Except that hashCode should be overridden, but that's a separate (upstream) issue.

**Comment by HelgeStenstrom** [comment]
Now I understand one of the issues that I wrote about 7 days ago. I can only
`import com.darkprograms.speech.util.Complex;`
not 
`import com.goxr3plus.speech.util.Complex;`
because I'm using release 8.0.0 (or the older V2.1), while the package structure has been changed since the last release, replacing darkprograms with goxr3plus.

**Comment by goxr3plus** [comment]
Whatever you want we can fix :)
